development:
  adapter: postgresql
  port: 5432
  username: postgres
  password: postgres
  database: event_schedules_dev
  host: localhost

test:
  adapter: postgresql
  port: 5432
  username: postgres
  password: postgres
  database: event_schedules_test
  host: localhost

